# Docker-Compose document
# Ref : https://docs.docker.com/compose/compose-file/

version: "3"
services:
  web:
    image: website:${TAG}
    container_name: web_service_${TAG}
    volumes:
      - ../cache/website/:/repo/node_modules/
      - ../cache/log/:/repo/app/log/
      - ../src/website/:/repo/
    networks:
      - service_network
    ports:
      - "8080:80"
    depends_on:
      - alg

  alg:
    image: algorithm:${TAG}
    container_name: alg_service_${TAG}
    volumes:
      - ../src/algorithm/:/repo/
    networks:
      - service_network
    ports:
      - "22:22"

networks:
  service_network:
    driver: bridge
